# Generated by Django 3.0.8 on 2020-07-04 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_auto_20200704_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randomtoken',
            name='token',
            field=models.CharField(editable=False, max_length=100),
        ),
    ]
